// <auto-generated />
using Employee_CRUD.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Employee_CRUD.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240424081915_SeedDataInDb")]
    partial class SeedDataInDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Employee_CRUD.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("Phone")
                        .HasMaxLength(10)
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "growwithanish@gmail.com",
                            Name = "Anish Shrestha",
                            Phone = 9845474900L
                        },
                        new
                        {
                            Id = 2,
                            Email = "aarjan@gmail.com",
                            Name = "Aarjan Shrestha",
                            Phone = 9876543210L
                        },
                        new
                        {
                            Id = 3,
                            Email = "shreni@gmail.com",
                            Name = "Shreni Shrestha",
                            Phone = 9807645321L
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
